package main

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"text/tabwriter"

	"github.com/pydpll/errorutils"
	"github.com/urfave/cli/v3"
)

func getBoilerplateDir() (string, error) {
	skriptujo := os.Getenv("scriptLoc")
	if skriptujo == "" {
		return "", fmt.Errorf("environment variable is not set for scriptLoc")
	}
	return filepath.Join(skriptujo, "boilerplate", "docker"), nil
}

// dockerEnv injects host UID/GID so compose bind mounts stay writable.
func dockerEnv() []string {
	return append(os.Environ(),
		fmt.Sprintf("UID=%d", os.Getuid()),
		fmt.Sprintf("GID=%d", os.Getgid()),
	)
}

// runCmd executes a command with stdin/stdout/stderr attached (interactive-safe).
func runCmd(ctx context.Context, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	cmd.Env = dockerEnv()
	return cmd.Run()
}

// runCmdQuiet runs a non-interactive command without attaching stdin
// (safe to call concurrently; used by netfix workers).
func runCmdQuiet(ctx context.Context, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = dockerEnv()
	return cmd.Run()
}

// runCmdOutput captures stdout (stderr still inherited for diagnostics).
func runCmdOutput(ctx context.Context, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, name, args...)
	var stdout bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = os.Stderr
	cmd.Env = dockerEnv()
	err := cmd.Run()
	return strings.TrimSpace(stdout.String()), err
}

// composeCfg carries project/stack options for docker compose invocations.
type composeCfg struct {
	project string
	stack   string
	hostNet bool
}

func cfgFromCLI(c *cli.Command) composeCfg {
	return composeCfg{
		project: c.String("project"),
		stack:   c.String("stack"),
		hostNet: c.Bool("host-net"),
	}
}

// writeHostNetOverride writes a temporary compose override that sets
// network_mode: host for one service. Does not modify project docker-compose.yml.
func writeHostNetOverride(service string) (string, error) {
	// Stable path so repeated compose calls in one process reuse the same file.
	path := filepath.Join(os.TempDir(), fmt.Sprintf("dokwerker-hostnet-%s.yml", service))
	content := fmt.Sprintf(`# Generated by dokwerker --host-net. Do not commit.
# Opt-in only: leaves project docker-compose.yml on default bridge networking.
services:
  %s:
    network_mode: host
`, service)
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return "", fmt.Errorf("write host-net override: %w", err)
	}
	return path, nil
}

// composeArgs builds a docker compose arg prefix.
// When hostNet is set, merges a temp override (network_mode: host) without
// changing the project's vendored/local compose file on disk permanently.
func composeArgs(cfg composeCfg, rest ...string) ([]string, error) {
	args := []string{"compose"}

	if cfg.hostNet {
		service, err := getServiceMapping(cfg.stack)
		if err != nil {
			return nil, err
		}
		override, err := writeHostNetOverride(service)
		if err != nil {
			return nil, err
		}
		// Explicit base + override so merge order is deterministic.
		args = append(args, "-f", "docker-compose.yml", "-f", override)
	}

	if cfg.project != "" {
		args = append(args, "-p", cfg.project)
	}
	return append(args, rest...), nil
}

// copyFile helper for initializing boilerplate files
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}

// getServiceMapping returns the default compose service name based on stack type
func getServiceMapping(stack string) (string, error) {
	switch stack {
	case "go":
		return "go-dev", nil
	case "ts":
		return "obsidian-dev", nil
	default:
		return "", fmt.Errorf("unknown stack type '%s' (use 'go' or 'ts')", stack)
	}
}

// InitAction copies boilerplate docker-compose and dockerfile to current dir
func InitAction(ctx context.Context, c *cli.Command) error {
	boilerplateDir, err := getBoilerplateDir()
	if err != nil {
		return err
	}
	stack := c.String("stack")
	fmt.Printf("Initializing project with %s stack boilerplate...\n", stack)

	var srcCompose, srcDockerfile string
	switch stack {
	case "go":
		srcCompose = filepath.Join(boilerplateDir, "go-docker-compose.yml")
		srcDockerfile = filepath.Join(boilerplateDir, "go-dockfile")
	case "ts":
		srcCompose = filepath.Join(boilerplateDir, "ts-docker-compose.yml")
		srcDockerfile = filepath.Join(boilerplateDir, "ts-dockerfile")
	default:
		return fmt.Errorf("unsupported stack: %s", stack)
	}

	if err := copyFile(srcCompose, "docker-compose.yml"); err != nil {
		return fmt.Errorf("failed to copy compose file (is $scriptLoc set correctly?): %w", err)
	}
	if err := copyFile(srcDockerfile, "Dockerfile"); err != nil {
		return fmt.Errorf("failed to copy dockerfile: %w", err)
	}

	fmt.Println("Boilerplate files successfully created (docker-compose.yml & Dockerfile).")
	if c.Bool("host-net") {
		fmt.Println("Note: --host-net does not change init output; pass it on up/shell/fresh to opt in at runtime.")
	}
	return nil
}

// UpAction builds and starts the compose stack
func UpAction(ctx context.Context, c *cli.Command) error {
	cfg := cfgFromCLI(c)
	args, err := composeArgs(cfg, "up", "-d", "--build")
	if err != nil {
		return err
	}

	if cfg.hostNet {
		service, _ := getServiceMapping(cfg.stack)
		fmt.Printf("Host networking ON for service '%s' (temp compose override; project file unchanged).\n", service)
		fmt.Println("Linux only: container shares the host network stack (no bridge isolation).")
	} else {
		fmt.Println("Building and starting docker compose stack (default bridge network)...")
	}
	return runCmd(ctx, "docker", args...)
}

// serviceContainerID returns the first container ID for a compose service (any state).
// Prefer a running container when both exist.
func serviceContainerID(ctx context.Context, cfg composeCfg, service string) (string, error) {
	// Running first.
	psArgs, err := composeArgs(cfg, "ps", "-q", "--status", "running", service)
	if err != nil {
		return "", err
	}
	out, err := runCmdOutput(ctx, "docker", psArgs...)
	if err == nil && out != "" {
		return strings.Fields(out)[0], nil
	}

	// Fallback: any state (or older compose without --status).
	psArgs, err = composeArgs(cfg, "ps", "-aq", service)
	if err != nil {
		return "", err
	}
	out, err = runCmdOutput(ctx, "docker", psArgs...)
	if err != nil {
		// Last resort without -a filter semantics differing across versions.
		psArgs, err = composeArgs(cfg, "ps", "-q", service)
		if err != nil {
			return "", err
		}
		out, err = runCmdOutput(ctx, "docker", psArgs...)
		if err != nil {
			return "", fmt.Errorf("could not resolve container for service %q: %w", service, err)
		}
	}
	if out == "" {
		return "", fmt.Errorf("no container found for service %q", service)
	}
	return strings.Fields(out)[0], nil
}

// ensureServiceRunning starts the stack if the target service has no running container.
func ensureServiceRunning(ctx context.Context, cfg composeCfg, service string) error {
	psArgs, err := composeArgs(cfg, "ps", "-q", "--status", "running", service)
	if err != nil {
		return err
	}
	out, err := runCmdOutput(ctx, "docker", psArgs...)
	if err != nil {
		// Older compose may not support --status; fall back to plain ps -q.
		psArgs, err = composeArgs(cfg, "ps", "-q", service)
		if err != nil {
			return err
		}
		out, err = runCmdOutput(ctx, "docker", psArgs...)
		if err != nil {
			return fmt.Errorf("could not query compose service status: %w", err)
		}
	}
	if out != "" {
		return nil
	}

	fmt.Printf("Service '%s' is not running; starting stack...\n", service)
	upArgs, err := composeArgs(cfg, "up", "-d", "--build")
	if err != nil {
		return err
	}
	if cfg.hostNet {
		fmt.Printf("Host networking ON for service '%s' (temp override).\n", service)
	}
	return runCmd(ctx, "docker", upArgs...)
}

// listContainerIDs returns running container IDs.
// When project is set, scopes to that compose project; otherwise all running containers.
func listContainerIDs(ctx context.Context, cfg composeCfg) ([]string, error) {
	var out string
	var err error
	if cfg.project != "" || cfg.hostNet {
		args, aerr := composeArgs(cfg, "ps", "-q")
		if aerr != nil {
			return nil, aerr
		}
		out, err = runCmdOutput(ctx, "docker", args...)
	} else {
		out, err = runCmdOutput(ctx, "docker", "ps", "-q")
	}
	if err != nil {
		return nil, err
	}
	if out == "" {
		return nil, nil
	}
	return strings.Fields(out), nil
}

// containerNetworks returns network names attached to a container.
func containerNetworks(ctx context.Context, containerID string) ([]string, error) {
	// Go template: print each attached network name, one per line.
	format := `{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{"\n"}}{{end}}`
	out, err := runCmdOutput(ctx, "docker", "inspect", "-f", format, containerID)
	if err != nil {
		return nil, err
	}
	if out == "" {
		return nil, nil
	}
	return strings.Fields(out), nil
}

// containerNetworkMode returns HostConfig.NetworkMode (e.g. "host", "bridge", "default").
func containerNetworkMode(ctx context.Context, containerID string) (string, error) {
	out, err := runCmdOutput(ctx, "docker", "inspect", "-f", "{{.HostConfig.NetworkMode}}", containerID)
	if err != nil {
		return "", err
	}
	return out, nil
}

// reconnectContainer force-disconnects and reconnects every network on one container.
func reconnectContainer(ctx context.Context, containerID string) (int, error) {
	mode, _ := containerNetworkMode(ctx, containerID)
	if mode == "host" {
		// Host netns has no bridge endpoints to bounce.
		return 0, nil
	}

	nets, err := containerNetworks(ctx, containerID)
	if err != nil {
		return 0, fmt.Errorf("inspect %s: %w", shortID(containerID), err)
	}
	if len(nets) == 0 {
		return 0, nil
	}

	var firstErr error
	ok := 0
	for _, n := range nets {
		// -f: required when the endpoint is in a half-dead state (common after sleep/VPN).
		if err := runCmdQuiet(ctx, "docker", "network", "disconnect", "-f", n, containerID); err != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("disconnect %s from %s: %w", shortID(containerID), n, err)
			}
			continue
		}
		if err := runCmdQuiet(ctx, "docker", "network", "connect", n, containerID); err != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("connect %s to %s: %w", shortID(containerID), n, err)
			}
			continue
		}
		ok++
	}
	return ok, firstErr
}

func shortID(id string) string {
	if len(id) > 12 {
		return id[:12]
	}
	return id
}

// netfixContainers force-reconnects networks for the given container IDs in parallel.
func netfixContainers(ctx context.Context, ids []string, scope string) error {
	if len(ids) == 0 {
		fmt.Printf("No containers to reconnect (%s).\n", scope)
		return nil
	}

	fmt.Printf("Reconnecting networks for %d container(s) (%s)...\n", len(ids), scope)

	var (
		wg       sync.WaitGroup
		mu       sync.Mutex
		totalOK  int
		failures []string
		skipped  int
	)

	// Bound concurrency so we don't stampede the Docker daemon.
	sem := make(chan struct{}, 8)

	for _, id := range ids {
		id := id
		wg.Add(1)
		go func() {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			n, err := reconnectContainer(ctx, id)
			mu.Lock()
			defer mu.Unlock()
			totalOK += n
			if err != nil {
				failures = append(failures, err.Error())
			} else if n > 0 {
				fmt.Printf("  %s: reconnected %d network(s)\n", shortID(id), n)
			} else {
				// host mode or no networks
				mode, _ := containerNetworkMode(ctx, id)
				if mode == "host" {
					skipped++
					fmt.Printf("  %s: host network (nothing to reconnect)\n", shortID(id))
				}
			}
		}()
	}
	wg.Wait()

	fmt.Printf("Done: %d network endpoint(s) reconnected", totalOK)
	if skipped > 0 {
		fmt.Printf(", %d host-network container(s) skipped", skipped)
	}
	fmt.Println(".")
	if len(failures) > 0 {
		return fmt.Errorf("netfix completed with %d error(s):\n  %s", len(failures), strings.Join(failures, "\n  "))
	}
	return nil
}

// netfixService reconnects only the target compose service's container.
func netfixService(ctx context.Context, cfg composeCfg, service string) error {
	id, err := serviceContainerID(ctx, cfg, service)
	if err != nil {
		return err
	}
	scope := fmt.Sprintf("service '%s'", service)
	if cfg.project != "" {
		scope = fmt.Sprintf("service '%s' in project '%s'", service, cfg.project)
	}
	return netfixContainers(ctx, []string{id}, scope)
}

// NetfixAction reconnects every running container to its networks.
// Drop-in replacement for the bash double-loop; runs containers in parallel.
//
// Equivalent shell (serial):
//
//	for c in $(docker ps -q); do
//	  for n in $(docker inspect -f '{{range $k,$v := .NetworkSettings.Networks}}{{$k}} {{end}}' "$c"); do
//	    docker network disconnect -f "$n" "$c" && docker network connect "$n" "$c"
//	  done
//	done
func NetfixAction(ctx context.Context, c *cli.Command) error {
	cfg := cfgFromCLI(c)
	// Optional: scope to the stack's mapped service only.
	if c.Bool("service-only") {
		service, err := getServiceMapping(cfg.stack)
		if err != nil {
			return err
		}
		return netfixService(ctx, cfg, service)
	}

	ids, err := listContainerIDs(ctx, cfg)
	if err != nil {
		return fmt.Errorf("list containers: %w", err)
	}
	if len(ids) == 0 {
		if cfg.project != "" {
			fmt.Printf("No running containers for project '%s'.\n", cfg.project)
		} else {
			fmt.Println("No running containers.")
		}
		return nil
	}

	scope := "all running containers"
	if cfg.project != "" {
		scope = fmt.Sprintf("project '%s'", cfg.project)
	}
	return netfixContainers(ctx, ids, scope)
}

// probeService runs a non-interactive true inside the service to verify exec works.
// Used so we only netfix on connectivity failures, not on interactive bash exit codes.
func probeService(ctx context.Context, cfg composeCfg, service string) error {
	args, err := composeArgs(cfg, "exec", "-T", service, "true")
	if err != nil {
		return err
	}
	return runCmdQuiet(ctx, "docker", args...)
}

// recreateService force-recreates the service (used when host-net recovery needs a clean netns).
func recreateService(ctx context.Context, cfg composeCfg, service string) error {
	fmt.Printf("Force-recreating service '%s'...\n", service)
	args, err := composeArgs(cfg, "up", "-d", "--build", "--force-recreate", "--no-deps", service)
	if err != nil {
		return err
	}
	return runCmd(ctx, "docker", args...)
}

// ShellAction jumps straight into the container's bash shell.
// Auto-starts a stopped stack; if exec is broken (stale networks), netfixes only that service
// (or force-recreates when --host-net is set — bridge reconnect does not apply).
func ShellAction(ctx context.Context, c *cli.Command) error {
	cfg := cfgFromCLI(c)
	service, err := getServiceMapping(cfg.stack)
	if err != nil {
		return err
	}

	if err := ensureServiceRunning(ctx, cfg, service); err != nil {
		return fmt.Errorf("could not ensure service is running: %w", err)
	}

	// Probe first so a later interactive bash exit code is never mistaken for a Docker failure.
	if err := probeService(ctx, cfg, service); err != nil {
		if cfg.hostNet {
			fmt.Printf("Container exec probe failed (%v); force-recreating with host network...\n", err)
			if rcErr := recreateService(ctx, cfg, service); rcErr != nil {
				return fmt.Errorf("host-net recreate failed: %w (original probe: %v)", rcErr, err)
			}
		} else {
			fmt.Printf("Container exec probe failed (%v); reconnecting networks for service '%s' only...\n", err, service)
			if nfErr := netfixService(ctx, cfg, service); nfErr != nil {
				fmt.Printf("Network reconnect warning: %v\n", nfErr)
			}
			if upErr := ensureServiceRunning(ctx, cfg, service); upErr != nil {
				return fmt.Errorf("service unreachable after netfix: %w (original probe: %v)", upErr, err)
			}
		}
		if err := probeService(ctx, cfg, service); err != nil {
			return fmt.Errorf("shell still unreachable after recovery: %w (try 'dokwerker fresh' or 'dokwerker netfix')", err)
		}
	}

	// -it: allocate a TTY so interactive tools work.
	args, err := composeArgs(cfg, "exec", "-it", service, "bash")
	if err != nil {
		return err
	}
	modeNote := "bridge"
	if cfg.hostNet {
		modeNote = "host-net requested"
	}
	fmt.Printf("Entering container shell for service '%s' (%s)...\n", service, modeNote)
	if err := runCmd(ctx, "docker", args...); err != nil {
		// Non-zero from bash itself (e.g. exit 1) — pass through unchanged.
		return err
	}
	return nil
}

// composeRow is one line of docker compose ps output we care about.
type composeRow struct {
	ID      string
	Name    string
	Service string
	State   string
	Status  string
}

// listComposeRows returns compose services (including stopped) for the project.
func listComposeRows(ctx context.Context, cfg composeCfg) ([]composeRow, error) {
	// Prefer modern compose format placeholders.
	format := `{{.ID}}\t{{.Name}}\t{{.Service}}\t{{.State}}\t{{.Status}}`
	args, err := composeArgs(cfg, "ps", "-a", "--format", format)
	if err != nil {
		return nil, err
	}
	out, err := runCmdOutput(ctx, "docker", args...)
	if err != nil {
		// Fallback without -a / format differences.
		args, aerr := composeArgs(cfg, "ps", "--format", format)
		if aerr != nil {
			return nil, aerr
		}
		out, err = runCmdOutput(ctx, "docker", args...)
		if err != nil {
			return nil, fmt.Errorf("docker compose ps: %w", err)
		}
	}
	if out == "" {
		return nil, nil
	}

	var rows []composeRow
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.Split(line, "\t")
		// Pad missing fields so partial format still works.
		for len(parts) < 5 {
			parts = append(parts, "")
		}
		rows = append(rows, composeRow{
			ID:      parts[0],
			Name:    parts[1],
			Service: parts[2],
			State:   parts[3],
			Status:  parts[4],
		})
	}
	return rows, nil
}

// StatusAction prints running/stopped compose services with attached networks.
func StatusAction(ctx context.Context, c *cli.Command) error {
	cfg := cfgFromCLI(c)
	targetService, mapErr := getServiceMapping(cfg.stack)
	if mapErr != nil {
		// Still show status even if stack flag is weird; just no highlight.
		targetService = ""
	}

	// Header context.
	if cfg.project != "" {
		fmt.Printf("Compose project: %s\n", cfg.project)
	} else {
		fmt.Println("Compose project: (default from cwd docker-compose.yml)")
	}
	if targetService != "" {
		fmt.Printf("Stack target:    %s → service %s\n", cfg.stack, targetService)
	}
	if cfg.hostNet {
		fmt.Println("Host-net flag:   on (status uses host-net override merge; running containers keep the mode they were created with)")
	} else {
		fmt.Println("Host-net flag:   off (default bridge unless container was created with --host-net)")
	}
	fmt.Println()

	rows, err := listComposeRows(ctx, cfg)
	if err != nil {
		return err
	}
	if len(rows) == 0 {
		fmt.Println("No containers for this compose project.")
		fmt.Println("Hint: run 'dokwerker up' or 'dokwerker fresh' first.")
		return nil
	}

	tw := tabwriter.NewWriter(os.Stdout, 0, 4, 2, ' ', 0)
	fmt.Fprintln(tw, "SERVICE\tSTATE\tSTATUS\tCONTAINER\tNET MODE\tNETWORKS\tNOTE")

	running := 0
	for _, r := range rows {
		nets := "-"
		netMode := "-"
		if r.ID != "" {
			if mode, merr := containerNetworkMode(ctx, r.ID); merr == nil && mode != "" {
				netMode = mode
			} else if merr != nil {
				netMode = "?"
			}
			if nlist, nerr := containerNetworks(ctx, r.ID); nerr == nil && len(nlist) > 0 {
				nets = strings.Join(nlist, ",")
			} else if nerr != nil {
				nets = "(inspect failed)"
			} else if netMode == "host" {
				nets = "(host stack)"
			} else {
				nets = "(none)"
			}
		}

		state := r.State
		if state == "" {
			state = "?"
		}
		if strings.EqualFold(state, "running") {
			running++
		}

		note := ""
		if targetService != "" && r.Service == targetService {
			note = "← shell target"
		}

		fmt.Fprintf(tw, "%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
			orDash(r.Service),
			state,
			orDash(r.Status),
			shortID(r.ID),
			netMode,
			nets,
			note,
		)
	}
	_ = tw.Flush()

	fmt.Printf("\n%d/%d container(s) running\n", running, len(rows))
	return nil
}

func orDash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}

// DownAction tears down the compose stack
func DownAction(ctx context.Context, c *cli.Command) error {
	cfg := cfgFromCLI(c)
	args, err := composeArgs(cfg, "down")
	if err != nil {
		return err
	}

	fmt.Println("Stopping and cleaning up stack containers...")
	return runCmd(ctx, "docker", args...)
}

func main() {
	cmd := &cli.Command{
		Name:  "dokwerker",
		Usage: "Generalized workflow manager for Go and TypeScript Docker development",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "stack",
				Aliases: []string{"s"},
				Value:   "go",
				Usage:   "Target technology stack (go or ts)",
			},
			&cli.StringFlag{
				Name:    "project",
				Aliases: []string{"p"},
				Value:   "",
				Usage:   "Optional Docker Compose project name (e.g. bibtex-1)",
			},
			&cli.BoolFlag{
				Name:    "host-net",
				Aliases: []string{"H"},
				Value:   false,
				Usage:   "Opt-in: run the stack service with network_mode=host via a temp compose override (Linux; does not modify docker-compose.yml)",
			},
		},
		Commands: []*cli.Command{
			{
				Name:   "init",
				Usage:  "Copy boilerplate Docker files into the current directory",
				Action: InitAction,
			},
			{
				Name:   "up",
				Usage:  "Build and launch the Docker Compose stack in the background",
				Action: UpAction,
			},
			{
				Name:   "shell",
				Usage:  "Exec into the dev container (auto-starts if down; recovers network on failure)",
				Action: ShellAction,
			},
			{
				Name:    "netfix",
				Aliases: []string{"reconnect", "fixnet"},
				Usage:   "Force-reconnect running containers to their Docker networks (fast sleep/VPN recovery)",
				Flags: []cli.Flag{
					&cli.BoolFlag{
						Name:    "service-only",
						Aliases: []string{"S"},
						Usage:   "Only reconnect the stack's mapped service (from --stack), not every container",
					},
				},
				Action: NetfixAction,
			},
			{
				Name:    "status",
				Aliases: []string{"ps", "st"},
				Usage:   "Show compose services: state, container id, network mode, and networks",
				Action:  StatusAction,
			},
			{
				Name:   "down",
				Usage:  "Stop and remove project containers",
				Action: DownAction,
			},
			{
				Name:    "fresh",
				Aliases: []string{"reset"},
				Usage:   "Initialize (if needed), bring up the build, and jump right into the shell",
				Action: func(ctx context.Context, c *cli.Command) error {
					// Optional: auto-init if files don't exist locally
					if _, err := os.Stat("docker-compose.yml"); err != nil {
						if !os.IsNotExist(err) {
							return fmt.Errorf("could not check for docker-compose.yml: %w", err)
						}
						if err := InitAction(ctx, c); err != nil {
							return fmt.Errorf("automatic initialization failed: %w", err)
						}
					}
					if err := UpAction(ctx, c); err != nil {
						return err
					}
					return ShellAction(ctx, c)
				},
			},
		},
	}

	if err := cmd.Run(context.Background(), os.Args); err != nil {
		errorutils.ExitOnFail(err)
	}
}
